---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false
  when: base_manage_swap | default(true)

- name: Remove swap from fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s.*)$'
    replace: '# \1'
  when: base_manage_swap | default(true)

- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernel_modules }}"
  when: base_manage_kernel_modules | default(true)

- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'
  when: base_manage_kernel_modules | default(true)

- name: Write sysctl settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
    content: |
      {% for item in sysctl_settings | dict2items %}
      {{ item.key }} = {{ item.value }}
      {% endfor %}

- name: Write inotify limits
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-inotify.conf
    mode: '0644'
    content: |
      fs.inotify.max_user_instances = {{ inotify_max_user_instances }}
      fs.inotify.max_user_watches = {{ inotify_max_user_watches }}

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - htop
      - dmsetup
      - pre-commit
      - python3
      - python3-dev
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gpg
      - npm
      - nodejs
    state: present
    update_cache: true

- name: Add nvtop PPA
  ansible.builtin.apt_repository:
    repo: ppa:quentiumyt/nvtop
    state: present
    update_cache: true

- name: Install nvtop
  ansible.builtin.apt:
    name: nvtop
    state: present
