apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:v0.39.0
        args:
        - -in-cluster
        - -plugins-dir=/headlamp/plugins
        env:
        - name: HEADLAMP_CONFIG_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: headlamp-oidc
              key: client_id
        - name: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: headlamp-oidc
              key: client_secret
        - name: HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: headlamp-oidc
              key: issuer_url
        - name: HEADLAMP_CONFIG_OIDC_SCOPES
          valueFrom:
            secretKeyRef:
              name: headlamp-oidc
              key: scopes
        ports:
        - containerPort: 4466
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
