apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: default
  labels:
    app: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: ghcr.io/YOUR_GITHUB_USERNAME/homelab-docs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: default
spec:
  selector:
    app: docs
  ports:
  - port: 80
    targetPort: 80
