apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs
  namespace: docs
  annotations:
    tailscale.com/tags: tag:k8s
    tailscale.com/https: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - docs
  rules:
  - host: docs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
