apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-homelab
  namespace: default
  annotations:
    tailscale.com/tags: tag:k8s
    tailscale.com/https: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - hello-homelab
  rules:
  - host: hello-homelab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-homelab
            port:
              number: 80
