apiVersion: v1
kind: Service
metadata:
  name: hello-homelab
  namespace: default
  annotations:
    tailscale.com/hostname: "hello-homelab"
spec:
  selector:
    app: hello-homelab
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
