all:
  children:
    k8s_control_plane:
      hosts:
        control-plane-1:
          ansible_host: legion
          ansible_user: sudhanva

    k8s_workers:
      hosts: {}

    k8s_nodes:
      children:
        k8s_control_plane:
        k8s_workers:

    gpu_nvidia:
      hosts: {}

    gpu_intel:
      hosts: {}

    cpu_only:
      hosts: {}
