apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/external-secrets/external-secrets/v1.2.0/deploy/crds/bundle.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
