apiVersion: v1
kind: Service
metadata:
  name: tdarr
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: tdarr
    component: server
  ports:
    - name: webui
      port: 80
      targetPort: 8265
    - name: server
      port: 8266
      targetPort: 8266
