apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-dns
  namespace: tailscale-dns
data:
  Corefile: |
    sudhanva.me:53 {
        errors
        health
        ready
        template IN CNAME {
            match "^(.*)\\.sudhanva\\.me\\.$"
            answer "{{ .Name }} 60 IN CNAME gateway-envoy.ainu-herring.ts.net."
        }
        forward . 1.1.1.1 1.0.0.1
        cache 30
    }
