apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-dns
  namespace: tailscale-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        template IN CNAME {
            match "^docs\\.sudhanva\\.me\\.$"
            answer "{{ .Name }} 60 IN CNAME gateway-envoy.ainu-herring.ts.net."
        }
        forward . 100.100.100.100
        cache 30
    }
