apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-dns
  namespace: tailscale-dns
data:
  Corefile: |
    sudhanva.me:53 {
        errors
        health
        ready
        rewrite name regex (.*)\\.sudhanva\\.me\\. gateway-envoy.ainu-herring.ts.net.
        forward . 100.100.100.100
        cache 30
    }
