apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-dns
  namespace: tailscale-dns
data:
  Corefile: |
    sudhanva.me:53 {
    errors
    health
    ready
    reload
    template IN A {
        answer "{{ .Name }} 60 IN A 100.109.53.92"
    }
        forward . 1.1.1.1 1.0.0.1
        cache 30
    }
