apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-dns
  namespace: tailscale-dns
data:
  Corefile: |
    sudhanva.me:53 {
        errors
        health
        ready
        template IN A {
            match "^(.*)\\.sudhanva\\.me\\.$"
            answer "{{ .Name }} 60 IN A 100.88.7.18"
        }
        forward . 1.1.1.1 1.0.0.1
        cache 30
    }
