apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      nodeSelector:
        kubernetes.io/hostname: legion
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: filebrowser
          image: docker.io/filebrowser/filebrowser
          args:
            - --root=/srv
            - --address=0.0.0.0
            - --port=8080
          env:
            - name: FB_DATABASE
              value: /database/filebrowser.db
            - name: FB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: filebrowser-auth
                  key: username
            - name: FB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filebrowser-auth
                  key: password_hash
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 300m
          volumeMounts:
            - name: media
              mountPath: /srv
            - name: config
              mountPath: /database
          ports:
            - containerPort: 8080
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-media
        - name: config
          persistentVolumeClaim:
            claimName: filebrowser-config
