apiVersion: v1
kind: Service
metadata:
  name: ntfy-alerts
  namespace: ntfy-alerts
spec:
  type: ClusterIP
  selector:
    app: ntfy-alerts
  ports:
  - name: http
    port: 8080
    targetPort: http
